# Why this Project 

The United State was founded on the belief that all people should be equal. Although the Fourteenth Amendment to the U.S Constitution guaranteed all citizens "equal protection of the laws", such protection is limited to state actions. People of different race, gender, religious belief etc still suffer from biases and discrimination. Hate Crimes, or bias-motivated crime, is one of the most dangerous consequence. 


A hate crime is a "criminal offense against a person or property motivated in whole or in part by an offender's bias against a race, religion, disability, sexual orientation, ethnicity, gender or gender identity." Hate crimes have server impact on our society in that damage is not limited to the immediate target of the crime, but to the entire group the victim represents. Hate crimes can cause  broad ripples of anger and stress among members of targeted group, and can trigger a wave of hate crimes. 

In light of recent tragedies such as the death of George Floyd, we want to know how much progress, if any, we've made in fighting against bias and discrimination. What populations, other than African Americans are susceptible to biases? In what region do hate crimes occur most frenquently? We resort to the New York Hate Crime data set to find answers. 