# Conclusion
We have successfully analyzed in this project the New York State hate crime data set. We now have a clear picture of how frequently each type of hate crime occurs in New York State, how hate crimes are distributed in each county and among all counties in the State, and the change in the number of total incidents between 2010 and 2018. 

Unfortunately, our data set does not include data on hate groups whose members may have committed or had direct involvement in some of these crimes. It would be productive to see the correlation between hate groups and hate crimes. For example, what type of hate crimes do particular hate groups commit most often? Do areas with high hate group activity also have a high number of hate crimes? Is there any correlation between the incidence of hate speech and that of hate crimes? These are all questions worth pursuing, as the answers to them can inform and sharpen our picture of hate crime in New York State.

It would also be interesting to analyze hate crimes across the entire United States. However, each state uses a different system for reporting hate crimes, and even have different criteria for defining hate crimes. For example, some states are more dedicated to the task of identifying hate crimes, whereas other states do not put as much effort into pursuing these cases because it is hard to cite tangible evidence of “hate” playing a role in the committing of a crime. According to CVI (the Crime Victims' Institute), the Hate Crimes Task Force of New York demonstrates an effective means to overcome the lack of proper data collection with respect to hate crimes. 

We noticed during our analysis that certain group of hate crime victims are more hesitant to report hate crimes due to a chronic distrust between their community and the police. For example, survey evidence shows that LGBTQ group often choose not to report hate crimes, meaning that many cases of hate crimes perpetuated against individuals from this community are not prosecuted as hate crimes even if they are prosecuted. Although we believe the total number of hate crimes is underreported, we are not certain whether a particular type of hate crime is underreported to a greater extent than others. It will be interesting to look at a data set of hate crimes experienced by victims, rather than only the hate crimes that were prosecuted.
